use_frameworks!

platform :ios, '9.0'

target 'MKNBJplugApp_Example' do
  pod 'MKNBJplugApp', :path => '../'

  target 'MKNBJplugApp_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
